version: 1.1.{build}-{branch}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- cmd: dotnet build -c Release -v m
test_script:
- cmd: dotnet test ./tests/Infra.Crosscutting.Tests/ -c Release
- cmd: dotnet test ./tests/Infra.Data.Seedwork.Tests/ -c Release
- cmd: dotnet test ./tests/Domain.Seedwork.Tests/ -c Release
artifacts:
- path: src\**\*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: vWFYEUtBwr4DHLeR8Kp8QDduqRKN7su4TBWXS2CE+V9Vg7BXvsKHMs140GCBmcFl
  skip_symbols: true
  on:
    branch: master