version: 1.2.{build}-{branch}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- ps: .\build.ps1 -Target Build -Configuration Release
test_script:
- ps: .\build.ps1 -Target Run-Tests -Configuration Release
after_test:
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f ".\.artifacts\Test-Results\OpenCover.xml" -t df44ee2d-7050-43a7-89a8-44aacbab58ea
before_deploy:
- ps: .\build.ps1 -Target Nuget-Pack -Configuration Release
deploy:
- provider: NuGet
  api_key:
    secure: 9dpId9X/l2OcN0X9HxwhMT0pbCWMbi9tEkmSC/xPkNLk2j5oVpTS0Yvbn0ke7/D9
  skip_symbols: true
  artifact: .\.artifacts\Nuget\*.nupkg
  on:
    branch: master
