language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131
script:
 - dotnet restore
 - dotnet build
 - dotnet test ./src/Aritter.Infra.Crosscutting.Tests/Aritter.Infra.Crosscutting.Tests.csproj