version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- cmd: dotnet build --configuration release
test_script:
- cmd: >-
    dotnet test ./src/Infra.Crosscutting.Tests/
    dotnet test ./src/Infra.Data.Seedwork.Tests/
    dotnet test ./src/Domain.Seedwork.Tests/
    dotnet test ./src/Application.Seedwork.Tests/
artifacts:
- path: src\**\*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: RNo1ClS3IqGXKZQOx7AoUDSMFHj/erQgJrZuBGKR/A6k61aGNInSaB6fwG5rZchF
  skip_symbols: true
  artifact: src\**\*.nupkg
  on:
    branch: master