version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- cmd: dotnet build --configuration release
test_script:
- cmd: dotnet test ./src/Infra.Crosscutting.Tests/ --configuration release
- cmd: dotnet test ./src/Infra.Data.Seedwork.Tests/ --configuration release
- cmd: dotnet test ./src/Domain.Seedwork.Tests/ --configuration release
artifacts:
- path: src\**\*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: RNo1ClS3IqGXKZQOx7AoUDSMFHj/erQgJrZuBGKR/A6k61aGNInSaB6fwG5rZchF
  skip_symbols: true
  on:
    branch: master