version: '{branch}.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- dotnet restore
build_script:
- dotnet build Aritter.sln -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet test "src\Aritter.Infra.Crosscutting.Tests\Aritter.Infra.Crosscutting.Tests.csproj"
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'