version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build
clone_depth: 1
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test ./src/Infra.Crosscutting.Tests/
  - cmd: dotnet test ./src/Infra.Data.Seedwork.Tests/
  - cmd: dotnet test ./src/Domain.Seedwork.Tests/
  - cmd: dotnet test ./src/Application.Seedwork.Tests/
deploy: off