version: '{branch}.{build}'
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build:
  project: .\src\Ritter.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - .\src\Infra.Crosscutting.Tests\Infra.Crosscutting.Tests.csproj
    - .\src\Domain.Seedwork.Tests\Domain.Seedwork.Tests.csproj
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'