version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Aritter.Infra.Crosscutting" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Aritter.Domain.Seedwork" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Aritter.Infra.Data.Seedwork" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Aritter.Application.Seedwork" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Aritter.API.Seedwork" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\Aritter.Infra.Crosscutting" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Aritter.Domain.Seedwork" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Aritter.Infra.Data.Seedwork" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Aritter.Application.Seedwork" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Aritter.API.Seedwork" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'